"use client"

import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Clock, Tag, Hourglass, DollarSign, MapPin, Star, Sparkles, ChevronDown, ChevronUp } from "lucide-react"
import { ItineraryDay, Activity } from "../types/workspace"

interface WorkspaceItineraryProps {
  timeline: ItineraryDay[]
}

export function WorkspaceItinerary({ timeline }: WorkspaceItineraryProps) {
  const [expandedAct, setExpandedAct] = React.useState<Record<number, boolean>>({})

  const toggleExpand = (actId: number) => {
    setExpandedAct((prev) => ({ ...prev, [actId]: !prev[actId] }))
  }

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-2">
        <div>
          <h2 className="text-lg font-black text-slate-800 dark:text-slate-100">
            Interactive Live Itinerary
          </h2>
          <p className="text-xs font-semibold text-slate-450 dark:text-slate-500 mt-0.5">
            Optimize your days, swap activities, and explore details generated by VoyageAI.
          </p>
        </div>
      </div>

      <div className="relative pl-6 border-l-2 border-slate-100 dark:border-slate-800 space-y-10">
        {timeline.map((day) => (
          <div key={day.id} className="relative">
            {/* Timeline day header marker */}
            <div className="absolute -left-[35px] top-1.5 bg-white dark:bg-slate-900 p-0.5 rounded-full z-10">
              <span className="size-4 bg-primary-blue rounded-full border-4 border-blue-50 dark:border-blue-950/60 block" />
            </div>

            <div className="mb-4">
              <h3 className="text-sm font-black text-slate-850 dark:text-slate-100 uppercase tracking-wider flex items-center gap-2">
                Day {day.dayNumber}
                <span className="text-xs font-bold text-slate-400 dark:text-slate-500 normal-case tracking-normal">
                  — {day.description}
                </span>
              </h3>
            </div>

            {/* List of activities */}
            <div className="space-y-4">
              {day.activities.map((act) => {
                const isExpanded = expandedAct[act.id]

                return (
                  <motion.div
                    key={act.id}
                    layout="position"
                    whileHover={{ y: -1 }}
                    className="bg-white dark:bg-slate-900 border border-black/5 dark:border-white/5 rounded-3xl p-5 shadow-sm transition-all hover:shadow-md flex flex-col md:flex-row gap-5"
                  >
                    {/* Activity Image */}
                    {act.imageUrl && (
                      <div className="w-full md:w-44 h-32 rounded-2xl overflow-hidden shrink-0 relative bg-slate-100">
                        <img src={act.imageUrl} alt={act.name} className="size-full object-cover" />
                        <span className="absolute top-2 left-2 bg-black/60 backdrop-blur-md text-[9px] font-black text-white px-2.5 py-1 rounded-full uppercase tracking-wider">
                          {act.category}
                        </span>
                      </div>
                    )}

                    {/* Content */}
                    <div className="flex-1 flex flex-col justify-between">
                      <div>
                        {/* Upper row: Time & Rating */}
                        <div className="flex items-center justify-between">
                          <span className="inline-flex items-center gap-1 text-[10px] font-black text-primary-blue bg-blue-50/50 dark:bg-blue-950/20 px-2.5 py-1 rounded-full uppercase tracking-wider">
                            <Clock className="size-3" />
                            {act.time}
                          </span>
                          {act.rating && (
                            <div className="flex items-center gap-1 text-amber-500">
                              <Star className="size-3 fill-amber-500" />
                              <span className="text-[10px] font-black">{act.rating}</span>
                            </div>
                          )}
                        </div>

                        {/* Title */}
                        <h4 className="text-sm font-black text-slate-800 dark:text-slate-100 mt-2">
                          {act.name}
                        </h4>

                        {/* Badges metadata info */}
                        <div className="flex flex-wrap items-center gap-x-4 gap-y-2 mt-3 text-[10px] font-bold text-slate-450 dark:text-slate-500">
                          <div className="flex items-center gap-1">
                            <Hourglass className="size-3.5 text-slate-400" />
                            <span>{act.duration}</span>
                          </div>
                          <div className="flex items-center gap-1">
                            <DollarSign className="size-3.5 text-slate-400" />
                            <span>
                              {act.budget > 0 ? `$${act.budget}` : "Free Admission"}
                            </span>
                          </div>
                          {act.address && (
                            <div className="flex items-center gap-1">
                              <MapPin className="size-3.5 text-slate-400" />
                              <span className="truncate max-w-[150px]">{act.address}</span>
                            </div>
                          )}
                        </div>
                      </div>

                      {/* Expandable details */}
                      <div className="mt-3">
                        <AnimatePresence initial={false}>
                          {isExpanded ? (
                            <motion.div
                              initial={{ height: 0, opacity: 0 }}
                              animate={{ height: "auto", opacity: 1 }}
                              exit={{ height: 0, opacity: 0 }}
                              transition={{ duration: 0.2 }}
                              className="overflow-hidden"
                            >
                              <p className="text-xs font-semibold leading-relaxed text-slate-500 dark:text-slate-400 pt-2 border-t border-slate-50 dark:border-slate-800">
                                {act.description || "No description provided for this activity."}
                              </p>
                            </motion.div>
                          ) : null}
                        </AnimatePresence>

                        <button
                          onClick={() => toggleExpand(act.id)}
                          className="mt-3 inline-flex items-center gap-1 text-[10px] font-black text-slate-450 hover:text-slate-700 dark:text-slate-500 dark:hover:text-slate-350 transition-colors cursor-pointer"
                        >
                          {isExpanded ? (
                            <>
                              Hide details
                              <ChevronUp className="size-3.5" />
                            </>
                          ) : (
                            <>
                              View details
                              <ChevronDown className="size-3.5" />
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  </motion.div>
                )
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
