import { DashboardData } from "../types/dashboard"

export const MOCK_DASHBOARD_DATA: DashboardData = {
  travelerName: "Alex Traveler",
  membershipType: "Pro Member",
  upcomingTrip: {
    id: "trip-tokyo",
    destination: "Tokyo, Japan",
    daysToGo: 12,
    durationDays: 12,
  },
  insights: [
    {
      id: "insight-bali",
      type: "price",
      badgeText: "Price Drop",
      badgeType: "price-drop",
      content: "Flights to Bali are 18% cheaper right now.",
      actionText: "Book Now",
      actionLink: "/discover/bali",
      icon: "TrendingDown",
    },
    {
      id: "insight-swiss",
      type: "weather",
      badgeText: "Optimal Time",
      badgeType: "optimal-time",
      content: "Best weather in Switzerland starts next month.",
      actionText: "Plan Trip",
      actionLink: "/planner/new?destination=switzerland",
      icon: "Sun",
    },
  ],
  budget: {
    spent: 4250,
    totalBudget: 5500,
    breakdown: [
      { category: "Flights", amount: 1800, color: "#2563EB" },
      { category: "Accommodation", amount: 1450, color: "#10B981" },
      { category: "Activities", amount: 1000, color: "#94A3B8" },
    ],
  },
  trips: [
    {
      id: "trip-tokyo",
      destination: "Tokyo, Japan",
      startDate: "Oct 12",
      endDate: "Oct 24",
      status: "Fully Booked",
      statusType: "success",
      daysToGo: 12,
      image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80",
      travelers: [
        { name: "Alex Traveler", initials: "AT" },
        { name: "Sarah Smith", initials: "SS" },
        { name: "John Doe", initials: "JD" },
      ],
      quickActionText: "View Itinerary",
    },
    {
      id: "trip-iceland",
      destination: "Iceland Ring Road",
      startDate: "Dec 5",
      endDate: "Dec 15",
      status: "Action Needed",
      statusType: "warning",
      daysToGo: 160,
      image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=600&q=80",
      travelers: [
        { name: "Alex Traveler", initials: "AT" },
        { name: "Emma Watson", initials: "EW" },
      ],
      quickActionText: "Planning Phase",
    },
  ],
  recommendations: [
    {
      id: "rec-bali",
      destination: "Bali",
      country: "Indonesia",
      matchScore: 98,
      description: "Perfect for your beach relaxation preference.",
      image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80",
      bestSeason: "April–Oct",
      avgBudget: "₹45K",
      rating: 4.8,
    },
    {
      id: "rec-swiss",
      destination: "Swiss Alps",
      country: "Switzerland",
      matchScore: 92,
      description: "Matches your hiking activity history.",
      image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=600&q=80",
      bestSeason: "June–Aug",
      avgBudget: "₹120K",
      rating: 4.9,
    },
    {
      id: "rec-dubai",
      destination: "Dubai",
      country: "UAE",
      matchScore: 85,
      description: "Trending destination based on your searches.",
      image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80",
      bestSeason: "Nov–March",
      avgBudget: "₹95K",
      rating: 4.7,
    },
  ],
  stats: [
    {
      id: "stat-countries",
      label: "Countries Visited",
      value: 14,
      icon: "Globe2",
      description: "Across 3 continents",
    },
    {
      id: "stat-trips",
      label: "Trips Completed",
      value: 28,
      icon: "CheckCircle2",
      description: "In the past 5 years",
    },
    {
      id: "stat-years",
      label: "Years Traveling",
      value: 5,
      icon: "Calendar",
      description: "Active traveler profile",
    },
  ],

  // Upgraded Feature Mock Data
  morningBrief: {
    greeting: "Good Morning, Alex",
    bullets: [
      { id: "mb-tokyo", text: "Flights to Tokyo dropped 14%", type: "price" },
      { id: "mb-weather", text: "Rain expected next Thursday", type: "weather" },
      { id: "mb-visa", text: "Visa expires in 4 months", type: "visa" },
      { id: "mb-hotel", text: "Hotel prices increased 9%", type: "hotel" },
      { id: "mb-restaurants", text: "AI found 3 better restaurants", type: "restaurant" },
    ],
  },
  timeline: [
    {
      id: "tl-passport",
      timeLabel: "Today",
      title: "Passport Expiry Alert",
      description: "Passport expires in 8 months. Consider renewing soon.",
      type: "warning",
    },
    {
      id: "tl-flight",
      timeLabel: "Tomorrow",
      title: "Flight Price Alert",
      description: "Tokyo route pricing check scheduled by AI agent.",
      type: "info",
    },
    {
      id: "tl-hotel",
      timeLabel: "Next Week",
      title: "Hotel Check-in Reminder",
      description: "Pre-check-in available for Tokyo Grand Palace.",
      type: "success",
    },
    {
      id: "tl-trip",
      timeLabel: "12 Days",
      title: "Tokyo Trip Begins",
      description: "Departure flight departs at 10:15 AM from Terminal 3.",
      type: "alert",
    },
  ],
  travelScore: {
    readiness: 96,
    checklist: [
      { id: "score-flights", text: "Flights Booked", status: "success" },
      { id: "score-hotels", text: "Hotels Confirmed", status: "success" },
      { id: "score-budget", text: "Budget Optimized", status: "success" },
      { id: "score-weather", text: "Weather Checked", status: "success" },
      { id: "score-passport", text: "Passport Renewal Soon", status: "warning" },
    ],
  },
  map: {
    visitedCountries: 14,
    plannedDestinations: 2,
    wishlistDestinations: 8,
  },
}
